"""Repository ports (interfaces) for the auth domain - Repository Pattern."""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import Protocol

from app.infrastructure.models import RefreshToken, User


class UserRepository(Protocol):
    async def get_by_email(self, email: str) -> User | None: ...
    async def get_by_id(self, user_id: uuid.UUID) -> User | None: ...
    async def create(self, *, email: str, full_name: str, hashed_password: str) -> User: ...
    async def assign_roles(self, user: User, role_names: list[str]) -> None: ...
    async def update_password(self, user: User, hashed_password: str) -> None: ...
    async def list_users(self, *, offset: int, limit: int) -> tuple[list[User], int]: ...


class RefreshTokenRepository(Protocol):
    async def store(
        self, *, user_id: uuid.UUID, jti: str, expires_at: datetime
    ) -> RefreshToken: ...
    async def get_active(self, jti: str) -> RefreshToken | None: ...
    async def revoke(self, jti: str) -> None: ...


class PasswordResetRepository(Protocol):
    async def create(
        self, *, user_id: uuid.UUID, token_hash: str, expires_at: datetime
    ) -> None: ...
    async def consume(self, token_hash: str) -> uuid.UUID | None: ...
