from __future__ import annotations

from pydantic import BaseModel, Field

from legalos_common.rag.filters import SearchFilters
from legalos_common.rag.schemas import Citation, ConfidenceBreakdown, RetrievedSource, WebImageResult, WebSearchResult
from legalos_orchestrator.schemas import ConversationMessage, Intent, JurisdictionResult, ResearchScope


class ResearchRequest(BaseModel):
    query: str = Field(min_length=3, max_length=4000)
    jurisdiction: str | None = None
    scope: ResearchScope = ResearchScope.CORPUS
    document_id: str | None = None
    document_ids: list[str] | None = None
    doc_type: str | None = None
    history: list[ConversationMessage] = Field(default_factory=list, max_length=40)

    def search_filters(self) -> SearchFilters:
        return SearchFilters(
            doc_type=self.doc_type,
            document_id=self.document_id,
            document_ids=self.document_ids,
        )


class ResearchResponse(BaseModel):
    query: str
    intent: Intent
    jurisdiction: JurisdictionResult
    answer: str
    sources: list[RetrievedSource]
    web_sources: list[WebSearchResult] = Field(default_factory=list)
    web_images: list[WebImageResult] = Field(default_factory=list)
    suggestions: list[str] = Field(default_factory=list)
    citations: list[Citation]
    confidence: ConfidenceBreakdown
    trace: list[str]
    specialist_payload: dict = Field(default_factory=dict)
    disclaimer: str = (
        "This response is generated by an AI system for informational purposes only "
        "and does not constitute legal advice. Consult a licensed advocate before "
        "acting on this information."
    )


class TtsRequest(BaseModel):
    text: str = Field(min_length=1, max_length=8000)
    rewrite_for_speech: bool = True
