from __future__ import annotations

from pydantic import BaseModel, Field

from legalos_common.rag.filters import SearchFilters
from legalos_common.rag.schemas import Citation, ConfidenceBreakdown, RetrievedSource, WebImageResult, WebSearchResult
from legalos_orchestrator.schemas import ConversationMessage, Intent, JurisdictionResult, ResearchScope


class ResearchRequest(BaseModel):
    query: str = Field(min_length=3, max_length=4000)
    jurisdiction: str | None = None
    scope: ResearchScope = ResearchScope.CORPUS
    document_id: str | None = None
    document_ids: list[str] | None = None
    doc_type: str | None = None
    history: list[ConversationMessage] = Field(default_factory=list, max_length=40)
    session_id: str | None = None
    user_id: str | None = None

    def search_filters(self) -> SearchFilters:
        return SearchFilters(
            doc_type=self.doc_type,
            document_id=self.document_id,
            document_ids=self.document_ids,
        )


class ResearchResponse(BaseModel):
    query: str
    intent: Intent
    jurisdiction: JurisdictionResult
    answer: str
    sources: list[RetrievedSource]
    web_sources: list[WebSearchResult] = Field(default_factory=list)
    web_images: list[WebImageResult] = Field(default_factory=list)
    suggestions: list[str] = Field(default_factory=list)
    citations: list[Citation]
    confidence: ConfidenceBreakdown
    trace: list[str]
    specialist_payload: dict = Field(default_factory=dict)
    disclaimer: str = (
        "This response is generated by an AI system for informational purposes only "
        "and does not constitute legal advice. Consult a licensed advocate before "
        "acting on this information."
    )


class TtsRequest(BaseModel):
    text: str = Field(min_length=1, max_length=8000)
    rewrite_for_speech: bool = True
    language: str = Field(default="en-IN", description="Indian regional speech locale code")


# ---- Post-hearing courtroom action plan ----

class CourtroomAgendaItemIn(BaseModel):
    id: str = Field(min_length=1, max_length=64)
    label: str = Field(min_length=1, max_length=240)
    status: str = Field(default="pending", max_length=32)


class CourtroomActionsRequest(BaseModel):
    matter_title: str = Field(min_length=1, max_length=400)
    matter_type: str = Field(default="Civil", max_length=64)
    petitioner_name: str = Field(default="Petitioner Advocate", max_length=200)
    respondent_name: str = Field(default="Respondent Advocate", max_length=200)
    oral_verdict: str | None = Field(default=None, max_length=4000)
    disposition: str | None = Field(default=None, max_length=2000)
    issues_framed: list[str] = Field(default_factory=list, max_length=12)
    weaknesses_exposed: list[str] = Field(default_factory=list, max_length=12)
    coverage_summary: str | None = Field(default=None, max_length=2000)
    agenda: list[CourtroomAgendaItemIn] = Field(default_factory=list, max_length=16)
    transcript_excerpt: str | None = Field(default=None, max_length=8000)
    not_covered: list[str] = Field(default_factory=list, alias="notCovered", max_length=16)
    verified_cite_count: int | None = Field(default=None, alias="verifiedCiteCount")
    unverified_cite_count: int | None = Field(default=None, alias="unverifiedCiteCount")

    model_config = {"populate_by_name": True}


class CourtroomActionCta(BaseModel):
    kind: str = Field(description="research | mera_vakil | copy")
    query: str | None = None


class CourtroomProposedAction(BaseModel):
    id: str
    title: str
    description: str
    side: str
    priority: str
    timeframe: str
    category: str
    rationale: str = ""
    related_issue_ids: list[str] = Field(default_factory=list, alias="relatedIssueIds")
    cta: CourtroomActionCta | None = None

    model_config = {"populate_by_name": True}


class CourtroomResearchAngle(BaseModel):
    title: str
    query: str


class CourtroomMandatoryFact(BaseModel):
    """Fact that must be proved / established on the record."""

    id: str
    fact: str
    why_mandatory: str = Field(default="", alias="whyMandatory")
    how_to_prove: str = Field(default="", alias="howToProve")
    side: str = "petitioner"
    related_issue_ids: list[str] = Field(default_factory=list, alias="relatedIssueIds")

    model_config = {"populate_by_name": True}


class CourtroomOpponentFactDefense(BaseModel):
    """How to defend / rebut a fact advanced by the opposite side."""

    id: str
    opponent_fact: str = Field(alias="opponentFact")
    defense_strategy: str = Field(alias="defenseStrategy")
    evidence_needed: str = Field(default="", alias="evidenceNeeded")
    side: str = "petitioner"
    related_issue_ids: list[str] = Field(default_factory=list, alias="relatedIssueIds")

    model_config = {"populate_by_name": True}


class CourtroomActionsResponse(BaseModel):
    headline: str
    summary: str
    forum_hint: str | None = Field(default=None, alias="forumHint")
    limitation_flags: list[str] = Field(default_factory=list, alias="limitationFlags")
    actions: list[CourtroomProposedAction]
    mandatory_facts: list[CourtroomMandatoryFact] = Field(
        default_factory=list, alias="mandatoryFacts"
    )
    opponent_fact_defenses: list[CourtroomOpponentFactDefense] = Field(
        default_factory=list, alias="opponentFactDefenses"
    )
    documents_to_gather: list[str] = Field(default_factory=list, alias="documentsToGather")
    research_angles: list[CourtroomResearchAngle] = Field(
        default_factory=list, alias="researchAngles"
    )
    settlement_levers: list[str] = Field(default_factory=list, alias="settlementLevers")
    disclaimer: str

    model_config = {"populate_by_name": True, "serialize_by_alias": True}


# ---- Grounded courtroom hearing turn ----

class CourtroomTurnAgendaItem(BaseModel):
    id: str = Field(min_length=1, max_length=64)
    label: str = Field(min_length=1, max_length=240)
    status: str = Field(default="pending", max_length=32)


class CourtroomTurnExhibit(BaseModel):
    id: str = Field(min_length=1, max_length=64)
    title: str = Field(min_length=1, max_length=240)
    status: str = Field(default="pending", max_length=32)


class CourtroomTurnRequest(BaseModel):
    speaker: str = Field(pattern="^(judge|petitioner|respondent)$")
    matter_title: str = Field(min_length=1, max_length=400)
    matter_type: str = Field(default="Civil", max_length=64)
    petitioner_name: str = Field(default="Petitioner Advocate", max_length=200)
    respondent_name: str = Field(default="Respondent Advocate", max_length=200)
    hearing_phase: str | None = Field(default="submissions", max_length=64)
    force_closing: bool = False
    intervene: bool = False
    case_summary: str | None = Field(default=None, max_length=2000)
    facts: str | None = Field(default=None, max_length=4000)
    issues: str | None = Field(default=None, max_length=2000)
    relief_sought: str | None = Field(default=None, max_length=1000)
    agenda: list[CourtroomTurnAgendaItem] = Field(default_factory=list, max_length=16)
    focus_point_ids: list[str] = Field(default_factory=list, max_length=8)
    exhibits: list[CourtroomTurnExhibit] = Field(default_factory=list, max_length=20)
    transcript_excerpt: str | None = Field(default=None, max_length=8000)
    document_ids: list[str] = Field(default_factory=list, max_length=12)
    jurisdiction: str | None = Field(default=None, max_length=120)
    allow_web: bool = True
    persona_cue: str | None = Field(default=None, max_length=400)
    strategy_cue: str | None = Field(default=None, max_length=600)


class CourtroomVerifiedSource(BaseModel):
    id: str
    title: str
    citation: str = ""
    snippet: str = ""
    source_kind: str = Field(alias="sourceKind")  # corpus | document | web
    url: str | None = None
    document_id: str | None = Field(default=None, alias="documentId")
    verified: bool = True

    model_config = {"populate_by_name": True, "serialize_by_alias": True}


class CourtroomExhibitAction(BaseModel):
    exhibit_id: str = Field(alias="exhibitId")
    status: str  # pending | marked | admitted | rejected

    model_config = {"populate_by_name": True, "serialize_by_alias": True}


class CourtroomTurnResponse(BaseModel):
    speaker: str
    text: str
    text_hi: str | None = Field(default=None, alias="textHi")
    addresses_point_ids: list[str] = Field(
        default_factory=list, alias="addressesPointIds"
    )
    cite_source_ids: list[str] = Field(default_factory=list, alias="citeSourceIds")
    exhibit_actions: list[CourtroomExhibitAction] = Field(
        default_factory=list, alias="exhibitActions"
    )
    suggest_judge_intervene: bool = Field(default=False, alias="suggestJudgeIntervene")
    timeline_step: str | None = Field(default=None, alias="timelineStep")
    judge_state: str | None = Field(default=None, alias="judgeState")
    judge_note: str | None = Field(default=None, alias="judgeNote")
    verified_sources: list[CourtroomVerifiedSource] = Field(
        default_factory=list, alias="verifiedSources"
    )
    disclaimer: str

    model_config = {"populate_by_name": True, "serialize_by_alias": True}


# ---- Agentic courtroom turn (CourtMaster + role agents) ----

class CourtroomExtractedFact(BaseModel):
    id: str
    text: str
    side: str = "neutral"
    status: str = "asserted"
    source: str = "intake"


class CourtroomTranscriptTurn(BaseModel):
    role: str
    text: str


class CourtroomAgentTurnRequest(BaseModel):
    matter_title: str = Field(min_length=1, max_length=400)
    matter_type: str = Field(default="Civil", max_length=64)
    petitioner_name: str = Field(default="Petitioner Advocate", max_length=200)
    respondent_name: str = Field(default="Respondent Advocate", max_length=200)
    case_summary: str | None = Field(default=None, max_length=2000)
    facts: str | None = Field(default=None, max_length=4000)
    issues: str | None = Field(default=None, max_length=2000)
    relief_sought: str | None = Field(default=None, max_length=1000)
    agenda: list[CourtroomTurnAgendaItem] = Field(default_factory=list, max_length=16)
    exhibits: list[CourtroomTurnExhibit] = Field(default_factory=list, max_length=20)
    authorities: list[CourtroomVerifiedSource] = Field(default_factory=list, max_length=40)
    transcript_excerpt: str | None = Field(default=None, max_length=8000)
    transcript_turns: list[CourtroomTranscriptTurn] = Field(
        default_factory=list, alias="transcriptTurns", max_length=20
    )
    document_ids: list[str] = Field(default_factory=list, max_length=12)
    jurisdiction: str | None = Field(default=None, max_length=120)
    persona_cues: dict[str, str] = Field(default_factory=dict, alias="personaCues")
    strategy_cues: dict[str, str] = Field(default_factory=dict, alias="strategyCues")
    compressed_case: str | None = Field(default=None, alias="compressedCase", max_length=4000)
    extracted_facts: list[CourtroomExtractedFact] = Field(
        default_factory=list, alias="extractedFacts", max_length=16
    )
    running_memory: str | None = Field(default=None, alias="runningMemory", max_length=2000)
    scratchpads: dict[str, str] = Field(default_factory=dict)
    turn_index: int = Field(default=0, alias="turnIndex")
    counsel_turns: int = Field(default=0, alias="counselTurns")
    judge_turns: int = Field(default=0, alias="judgeTurns")
    closings_done: int = Field(default=0, alias="closingsDone")
    issues_framed: bool = Field(default=False, alias="issuesFramed")
    verdict_ready: bool = Field(default=False, alias="verdictReady")
    last_speaker: str | None = Field(default=None, alias="lastSpeaker")
    derived_phase: str | None = Field(default=None, alias="derivedPhase")
    force_end: bool = Field(default=False, alias="forceEnd")
    force_speaker: str | None = Field(default=None, alias="forceSpeaker")

    model_config = {"populate_by_name": True}


class CourtroomToolTraceItem(BaseModel):
    tool: str
    args: dict = Field(default_factory=dict)
    result: dict = Field(default_factory=dict)


class CourtroomBlackboardEcho(BaseModel):
    turn_index: int = Field(alias="turnIndex")
    counsel_turns: int = Field(alias="counselTurns")
    judge_turns: int = Field(alias="judgeTurns")
    closings_done: int = Field(alias="closingsDone")
    issues_framed: bool = Field(alias="issuesFramed")
    verdict_ready: bool = Field(alias="verdictReady")
    last_speaker: str | None = Field(default=None, alias="lastSpeaker")
    derived_phase: str = Field(alias="derivedPhase")
    agenda: list[CourtroomTurnAgendaItem] = Field(default_factory=list)
    exhibits: list[CourtroomTurnExhibit] = Field(default_factory=list)
    authorities: list[CourtroomVerifiedSource] = Field(default_factory=list)
    compressed_case: str | None = Field(default=None, alias="compressedCase")
    extracted_facts: list[CourtroomExtractedFact] = Field(
        default_factory=list, alias="extractedFacts"
    )
    running_memory: str | None = Field(default=None, alias="runningMemory")
    scratchpads: dict[str, str] = Field(default_factory=dict)
    transcript_turns: list[CourtroomTranscriptTurn] = Field(
        default_factory=list, alias="transcriptTurns"
    )

    model_config = {"populate_by_name": True, "serialize_by_alias": True}


class CourtroomAgentTurnResponse(BaseModel):
    speaker: str
    text: str
    text_hi: str | None = Field(default=None, alias="textHi")
    addresses_point_ids: list[str] = Field(
        default_factory=list, alias="addressesPointIds"
    )
    cite_source_ids: list[str] = Field(default_factory=list, alias="citeSourceIds")
    exhibit_actions: list[CourtroomExhibitAction] = Field(
        default_factory=list, alias="exhibitActions"
    )
    timeline_step: str | None = Field(default=None, alias="timelineStep")
    judge_state: str | None = Field(default=None, alias="judgeState")
    judge_note: str | None = Field(default=None, alias="judgeNote")
    is_verdict: bool = Field(default=False, alias="isVerdict")
    tool_trace: list[CourtroomToolTraceItem] = Field(
        default_factory=list, alias="toolTrace"
    )
    verified_sources: list[CourtroomVerifiedSource] = Field(
        default_factory=list, alias="verifiedSources"
    )
    blackboard: CourtroomBlackboardEcho | None = None
    disclaimer: str

    model_config = {"populate_by_name": True, "serialize_by_alias": True}