# Next.js standalone build. Build context MUST be the repository root.
FROM node:20-alpine AS deps
WORKDIR /app
COPY frontend/package.json frontend/package-lock.json* ./
RUN npm install --no-audit --no-fund

FROM node:20-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY frontend/ .
ENV NEXT_TELEMETRY_DISABLED=1
# NEXT_PUBLIC_* vars are baked at build time — pass them as build args
ARG NEXT_PUBLIC_GOOGLE_CLIENT_ID=""
ENV NEXT_PUBLIC_GOOGLE_CLIENT_ID=$NEXT_PUBLIC_GOOGLE_CLIENT_ID
ARG NEXT_PUBLIC_FEATURE_SAARTHI="true"
ENV NEXT_PUBLIC_FEATURE_SAARTHI=$NEXT_PUBLIC_FEATURE_SAARTHI
ARG NEXT_PUBLIC_FEATURE_VOICE="true"
ENV NEXT_PUBLIC_FEATURE_VOICE=$NEXT_PUBLIC_FEATURE_VOICE
ARG NEXT_PUBLIC_FEATURE_CASE_BRIEF="true"
ENV NEXT_PUBLIC_FEATURE_CASE_BRIEF=$NEXT_PUBLIC_FEATURE_CASE_BRIEF
ARG NEXT_PUBLIC_FEATURE_CASES="true"
ENV NEXT_PUBLIC_FEATURE_CASES=$NEXT_PUBLIC_FEATURE_CASES
ARG NEXT_PUBLIC_FEATURE_RESEARCH_CONSOLE="true"
ENV NEXT_PUBLIC_FEATURE_RESEARCH_CONSOLE=$NEXT_PUBLIC_FEATURE_RESEARCH_CONSOLE
ARG NEXT_PUBLIC_FEATURE_MARKETPLACE="true"
ENV NEXT_PUBLIC_FEATURE_MARKETPLACE=$NEXT_PUBLIC_FEATURE_MARKETPLACE
ARG NEXT_PUBLIC_FEATURE_AI_MATCHING="true"
ENV NEXT_PUBLIC_FEATURE_AI_MATCHING=$NEXT_PUBLIC_FEATURE_AI_MATCHING
ARG NEXT_PUBLIC_FEATURE_BOOKING="true"
ENV NEXT_PUBLIC_FEATURE_BOOKING=$NEXT_PUBLIC_FEATURE_BOOKING
ARG NEXT_PUBLIC_FEATURE_ROOM="true"
ENV NEXT_PUBLIC_FEATURE_ROOM=$NEXT_PUBLIC_FEATURE_ROOM
ARG NEXT_PUBLIC_FEATURE_WALLET="true"
ENV NEXT_PUBLIC_FEATURE_WALLET=$NEXT_PUBLIC_FEATURE_WALLET
RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production NEXT_TELEMETRY_DISABLED=1
RUN addgroup -g 1001 -S nodejs && adduser -S nextjs -u 1001
COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
USER nextjs
EXPOSE 3000
ENV PORT=3000 HOSTNAME=0.0.0.0
CMD ["node", "server.js"]
