"""Shared RAG response contracts. Every answer carries sources + citations + score."""

from __future__ import annotations

from pydantic import BaseModel, Field


class RetrievedSource(BaseModel):
    chunk_id: str
    document_id: str
    title: str | None = None
    doc_type: str | None = None
    jurisdiction: str | None = None
    citation: str | None = None
    section: str | None = None
    content: str
    score: float
    retrieval: str = "hybrid"  # vector | keyword | hybrid


class Citation(BaseModel):
    marker: str  # e.g. "[1]"
    title: str | None = None
    citation: str | None = None
    document_id: str
    section: str | None = None


class ConfidenceBreakdown(BaseModel):
    retrieval_strength: float = Field(ge=0.0, le=1.0)
    source_agreement: float = Field(ge=0.0, le=1.0)
    coverage: float = Field(ge=0.0, le=1.0)
    overall: float = Field(ge=0.0, le=1.0)


class WebSearchResult(BaseModel):
    title: str
    url: str
    snippet: str = ""


class WebImageResult(BaseModel):
    title: str
    image_url: str
    source_url: str = ""
    caption: str = ""


class RagAnswer(BaseModel):
    query: str
    answer: str
    sources: list[RetrievedSource]
    citations: list[Citation]
    confidence: ConfidenceBreakdown
    jurisdiction: str | None = None
    disclaimer: str = (
        "This response is generated by an AI system for informational purposes only "
        "and does not constitute legal advice. Consult a licensed advocate before "
        "acting on this information."
    )
