name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: AWS

    permissions:
      id-token: write  # Required for requesting the JWT
      contents: read   # Required for actions/checkout

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION || 'ap-south-1' }}

      - name: Set up Admin Credentials
        run: |
          echo "ADMIN_USERNAME=${{ secrets.ADMIN_USERNAME }}" >> $GITHUB_ENV
          echo "ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }}" >> $GITHUB_ENV

      - name: Deploy to AWS Lambda
        run: |
          chmod +x deploy_aws.sh
          ./deploy_aws.sh satyapan ${{ secrets.AWS_REGION || 'ap-south-1' }}
