/** Allowed parameter keys across all events. Unknown keys are stripped. */
export const ALLOWED_PARAM_KEYS = new Set([
  "page_path",
  "page_title",
  "page_type",
  "referrer_category",
  "cta_location",
  "cta_type",
  "destination",
  "entry_point",
  "account_type",
  "signup_method",
  "authentication_method",
  "utm_source",
  "utm_medium",
  "utm_campaign",
  "utm_content",
  "utm_term",
  "feature_name",
  "session_type",
  "interaction_type",
  "conversation_number",
  "has_attachment",
  "response_status",
  "latency_bucket",
  "has_citations",
  "message_count_bucket",
  "matter_category",
  "document_feature",
  "file_type_category",
  "file_size_bucket",
  "processing_status",
  "result_count_bucket",
  "filter_applied",
  "filter_type",
  "sort_type",
  "practice_area_category",
  "booking_source",
  "consultation_type",
  "appointment_mode",
  "duration_bucket",
  "price_bucket",
  "booking_status",
  "first_booking_free",
  "cancellation_stage",
  "consultation_mode",
  "completion_status",
  "payment_type",
  "amount_bucket",
  "modules_available_count",
  "error_type",
  "feedback_type",
]);

export type AnalyticsParamValue = string | number | boolean;

export type AnalyticsParams = Record<string, AnalyticsParamValue>;
