export interface CounselReportSource {
  title?: string;
  citation?: string;
  url?: string;
}

export interface CounselReportPayload {
  question: string;
  answer: string;
  sources?: CounselReportSource[];
  disclaimer?: string;
}

const CITATION_MARK = /\[(?:KB|WEB)-\d+\]/g;

export function stripCitationMarkers(text: string): string {
  return text.replace(CITATION_MARK, "").replace(/\n{3,}/g, "\n\n").trim();
}

export function reportStamp(date = new Date()): string {
  const y = date.getFullYear();
  const m = String(date.getMonth() + 1).padStart(2, "0");
  const d = String(date.getDate()).padStart(2, "0");
  return `${y}${m}${d}`;
}

export function counselReportFilename(date = new Date()): string {
  return `Saarthi-Counsel-Report-${reportStamp(date)}.pdf`;
}

export function formatCounselReportPlaintext(payload: CounselReportPayload): string {
  const question = stripCitationMarkers(payload.question || "—");
  const answer = stripCitationMarkers(payload.answer || "");
  const sources = (payload.sources ?? []).slice(0, 12);
  const disclaimer =
    payload.disclaimer?.trim() ||
    "This response is generated by an AI system for informational purposes only and does not constitute legal advice.";

  const sourceLines = sources
    .map((src, i) => {
      const title = src.title || src.citation || src.url || `Source ${i + 1}`;
      const extra = [src.citation, src.url].filter(Boolean).join(" · ");
      return extra && extra !== title ? `${i + 1}. ${title} — ${extra}` : `${i + 1}. ${title}`;
    })
    .join("\n");

  return [
    "MeraBakil · Saarthi counsel report",
    "",
    "Your question",
    question,
    "",
    "Counsel note",
    answer,
    "",
    sources.length ? "Sources" : "",
    sourceLines,
    "",
    "Disclaimer",
    disclaimer,
  ]
    .filter((line, i, arr) => !(line === "" && arr[i - 1] === ""))
    .join("\n")
    .trim();
}
